name: Build+Test

on: [ push, pull_request ]

jobs:
  buildtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Install stuff
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qqy install wget ca-certificates build-essential bison flex automake autoconf libtool pkg-config

    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: 1.22

    - name: Show info about build environment
      run: |
        pwd
        env
        cat /etc/debian_version
        go version
        gcc --version

    - name: Build YARA from source
      run: |
        YARA_VERSION=4.5.1
        wget --no-verbose -O- https://github.com/VirusTotal/yara/archive/v${YARA_VERSION}.tar.gz | tar -C .. -xzf -
        ( cd ../yara-${YARA_VERSION} && ./bootstrap.sh )
        mkdir -p ../yara-build
        ( cd ../yara-build && \
          ../yara-${YARA_VERSION}/configure --disable-shared --prefix=${HOME}/prefix )
        make -C ../yara-build install
        find ${HOME}/prefix

    - name: Build/Test
      run: |
        export PKG_CONFIG_PATH=${HOME}/prefix/lib/pkgconfig
        go test -v -tags yara_static ./...
